require:
  - rubocop-rails
  - rubocop-rspec

Rails:
  Enabled: true

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.3
  Exclude:
    - bin/**/*
    - db/**/*
    - node_modules/**/*
    - vendor/**/*
    - tmp/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 16
